package models.enums;

public enum PlantType {
    SUNFLOWER(PlantFamily.SUN_PRODUCER),
    TWIN_SUNFLOWER(PlantFamily.SUN_PRODUCER),
    SUN_SHROOM(PlantFamily.SUN_PRODUCER),
    PRIMAL_SUNFLOWER(PlantFamily.SUN_PRODUCER),
    GOLD_BLOOM(PlantFamily.SUN_PRODUCER),
    PEASHOOTER(PlantFamily.SHOOTER),
    REPEATER(PlantFamily.SHOOTER),
    THREEPEATER(PlantFamily.SHOOTER),
    SNOW_PEA(PlantFamily.SHOOTER),
    ROTOBAGA(PlantFamily.SHOOTER),
    PEA_POD(PlantFamily.SHOOTER),
    SPLIT_PEA(PlantFamily.SHOOTER),
    CITRON(PlantFamily.SHOOTER),
    CAULIPOWER(PlantFamily.HOMING),
    ELECTRIC_BLUEBERRY(PlantFamily.HOMING),
    BOWLING_BULB(PlantFamily.SHOOTER),
    CACTUS(PlantFamily.STRIKE_THROUGH),
    FIRE_PEASHOOTER(PlantFamily.SHOOTER),
    STARFRUIT(PlantFamily.SHOOTER),
    GOO_PEASHOOTER(PlantFamily.SHOOTER),
    MEGA_GATLING_PEA(PlantFamily.SHOOTER),
    SEA_SHROOM(PlantFamily.SHOOTER),
    PUFF_SHROOM(PlantFamily.SHOOTER),
    FUME_SHROOM(PlantFamily.STRIKE_THROUGH),
    CABBAGE_PULT(PlantFamily.LOBBER),
    KERNEL_PULT(PlantFamily.LOBBER),
    MELON_PULT(PlantFamily.LOBBER),
    WINTER_MELON(PlantFamily.LOBBER),
    PEPPER_PULT(PlantFamily.LOBBER),
    POTATO_MINE(PlantFamily.EXPLOSIVE),
    PRIMAL_POTATO_MINE(PlantFamily.EXPLOSIVE),
    CHERRY_BOMB(PlantFamily.EXPLOSIVE),
    SQUASH(PlantFamily.EXPLOSIVE),
    GRAPESHOT(PlantFamily.EXPLOSIVE),
    JALAPENO(PlantFamily.EXPLOSIVE),
    DOOM_SHROOM(PlantFamily.EXPLOSIVE),
    TANGLE_KELP(PlantFamily.EXPLOSIVE),
    ICEBERG_LETTUCE(PlantFamily.EXPLOSIVE),
    BONK_CHOY(PlantFamily.MELEE),
    PHAT_BEET(PlantFamily.MELEE),
    CHOMPER(PlantFamily.MELEE),
    WASABI_WHIP(PlantFamily.MELEE),
    KIWIBEAST(PlantFamily.MELEE),
    WALL_NUT(PlantFamily.WALL_NUT),
    TALL_NUT(PlantFamily.WALL_NUT),
    ENDURIAN(PlantFamily.WALL_NUT),
    GARLIC(PlantFamily.WALL_NUT),
    SWEET_POTATO(PlantFamily.WALL_NUT),
    EXPLODE_O_NUT(PlantFamily.WALL_NUT),
    PUMPKIN(PlantFamily.WALL_NUT),
    SUN_BEAN(PlantFamily.WALL_NUT),
    TORCHWOOD(PlantFamily.MODIFIER),
    MAGNET_SHROOM(PlantFamily.HOMING),
    HYPNO_SHROOM(PlantFamily.MODIFIER),
    CAT_TAIL(PlantFamily.HOMING),
    IMITATER(PlantFamily.MODIFIER),
    ICE_SHROOM(PlantFamily.EXPLOSIVE),
    LILY_PAD(PlantFamily.MODIFIER),
    HOT_POTATO(PlantFamily.EXPLOSIVE),
    GRAVE_BUSTER(PlantFamily.EXPLOSIVE),
    ENLIGHTEN_MINT(PlantFamily.SUN_PRODUCER),
    APPEASE_MINT(PlantFamily.SHOOTER),
    ARMA_MINT(PlantFamily.LOBBER),
    BOMBARD_MINT(PlantFamily.EXPLOSIVE),
    ENFORCE_MINT(PlantFamily.MELEE),
    REINFORCE_MINT(PlantFamily.WALL_NUT),
    ENCHANT_MINT(PlantFamily.MODIFIER),
    PIERCE_MINT(PlantFamily.STRIKE_THROUGH),
    CAT_TAIL_MINT(PlantFamily.HOMING);

    public final PlantFamily family;
    PlantType(PlantFamily family){
        this.family = family;
    }
}
