package models.enums;

import static models.enums.PlantFamily.*;

public enum PlantType {
    SUNFLOWER(SUN_PRODUCER, 50, 50),
    TWIN_SUNFLOWER(SUN_PRODUCER, 125, 15),
    SUN_SHROOM(SUN_PRODUCER, 25, 5),
    PRIMAL_SUNFLOWER(SUN_PRODUCER, 75, 5),
    GOLD_BLOOM(SUN_PRODUCER, 0, 75),
    PEASHOOTER(SHOOTER, 100, 5),
    REPEATER(SHOOTER, 200, 5),
    THREEPEATER(SHOOTER, 300, 5),
    SNOW_PEA(SHOOTER, 150, 5),
    ROTOBAGA(SHOOTER, 150, 5),
    PEA_POD(SHOOTER, 125, 5),
    SPLIT_PEA(SHOOTER, 125, 5),
    CITRON(SHOOTER, 350, 5),
    CAULIPOWER(HOMING, 250, 15),
    ELECTRIC_BLUEBERRY(HOMING, 150, 15),
    BOWLING_BULB(SHOOTER, 200, 5),
    CACTUS(STRIKE_THROUGH, 175, 5),
    FIRE_PEASHOOTER(SHOOTER, 175, 5),
    STARFRUIT(SHOOTER, 150, 5),
    GOO_PEASHOOTER(SHOOTER, 125, 5),
    MEGA_GATLING_PEA(SHOOTER, 400, 5),
    SEA_SHROOM(SHOOTER, 0, 15),
    PUFF_SHROOM(SHOOTER, 0, 5),
    FUME_SHROOM(STRIKE_THROUGH, 125, 5),
    CABBAGE_PULT(LOBBER, 100, 5),
    KERNEL_PULT(LOBBER, 100, 5),
    MELON_PULT(LOBBER, 325, 5),
    WINTER_MELON(LOBBER, 500, 5),
    PEPPER_PULT(LOBBER, 200, 5),
    POTATO_MINE(EXPLOSIVE, 25, 25),
    PRIMAL_POTATO_MINE(EXPLOSIVE, 50, 5),
    CHERRY_BOMB(EXPLOSIVE, 150, 35),
    SQUASH(EXPLOSIVE, 50, 20),
    GRAPESHOT(EXPLOSIVE, 150, 35),
    JALAPENO(EXPLOSIVE, 125, 35),
    DOOM_SHROOM(EXPLOSIVE, 125, 15),
    TANGLE_KELP(EXPLOSIVE, 25, 15),
    ICEBERG_LETTUCE(EXPLOSIVE, 0, 20),
    BONK_CHOY(MELEE, 150, 5),
    PHAT_BEET(MELEE, 150, 5),
    CHOMPER(MELEE, 150, 5),
    WASABI_WHIP(MELEE, 150, 5),
    KIWIBEAST(MELEE, 175, 5),
    WALL_NUT(WALL_NUTS, 50, 20),
    TALL_NUT(WALL_NUTS, 125, 20),
    ENDURIAN(WALL_NUTS, 100, 15),
    GARLIC(WALL_NUTS, 50, 20),
    SWEET_POTATO(WALL_NUTS, 150, 20),
    EXPLODE_O_NUT(WALL_NUTS, 50, 20),
    PUMPKIN(WALL_NUTS, 150, 20),
    SUN_BEAN(WALL_NUTS, 50, 20),
    TORCHWOOD(MODIFIER, 175, 5),
    MAGNET_SHROOM(HOMING, 100, 15),
    HYPNO_SHROOM(MODIFIER, 125, 20),
    CAT_TAIL(HOMING, 175, 20),
    IMITATOR(MODIFIER, 0, 0),
    ICE_SHROOM(EXPLOSIVE, 75, 50),
    LILY_PAD(MODIFIER, 25, 5),
    HOT_POTATO(EXPLOSIVE, 0, 5),
    GRAVE_BUSTER(EXPLOSIVE, 0, 10),
    ENLIGHTEN_MINT(SUN_PRODUCER, 0, 85),
    APPEASE_MINT(SHOOTER, 0, 85),
    ARMA_MINT(LOBBER, 0, 85),
    BOMBARD_MINT(EXPLOSIVE, 0, 85),
    ENFORCE_MINT(MELEE, 0, 85),
    REINFORCE_MINT(WALL_NUTS, 0, 85),
    ENCHANT_MINT(MODIFIER, 0, 85),
    PIERCE_MINT(STRIKE_THROUGH, 0, 85),
    CAT_TAIL_MINT(HOMING, 0, 85),
    MARIGOLD(WALL_NUTS, 0, 0); // گل معمولی گلخانه;

    public String getSymbol() {
        return switch (this.family) {
            case SUN_PRODUCER -> "🌻";
            case SHOOTER, HOMING, LOBBER, STRIKE_THROUGH, MODIFIER-> "🟢";
            case MELEE -> "🥊";
            case WALL_NUTS -> "🧱";
            case EXPLOSIVE -> "💥";
            default -> "🌱";
        };
    }

    public final PlantFamily family;
    public final int baseSunCost;
    public final int baseCoolDown;
    PlantType(PlantFamily family, int baseSunCost, int baseCoolDown){
        this.family = family;
        this.baseSunCost = baseSunCost;
        this.baseCoolDown = baseCoolDown;
    }
}
