package models.enums;

public enum ProjectileType {
    PEA("STRAIGHT"),
    ICE_PEA("STRAIGHT"),
    FIRE_PEA("STRAIGHT"),
    GIANT_PEA("STRAIGHT"),
    PLASMA("STRAIGHT"),
    CITRON("STRAIGHT"),
    ROTOBAGA_PROJECTILE("STRAIGHT"),
    CACTUS("STRAIGHT"),
    CACTUS_SPECIAL("STRAIGHT"),
    STAR("STAR"),
    GOO("STRAIGHT"),
    GOO_SPECIAL("STRAIGHT"),
    SMALL_SHROOM("STRAIGHT"),
    FUME("STRAIGHT"),
    FUME_SPECIAL("STRAIGHT"),
    SMALL_BULB("STRAIGHT"),
    MEDIUM_BULB("STRAIGHT"),
    LARGE_BULB("STRAIGHT"),
    SPECIAL_BULB("STRAIGHT"),
    CABBAGE("LOBBED"),
    SPECIAL_CABBAGE("LOBBED"),
    KERNEL("LOBBED"),
    BUTTER("LOBBED"),
    MELON("LOBBED"),
    SPECIAL_MELON("LOBBED"),
    PEPPER("LOBBED"),
    SPECIAL_PEPPER("LOBBED"),
    SPECIAL_ICE_MELON("LOBBED"),
    ICE_MELON("LOBBED");


    public final String movement;
    ProjectileType(String movement) {this.movement = movement;}
}
