[compileJava, compileTestJava]*.options*.encoding = 'UTF-8'
eclipse.project.name = appName + '-core'

dependencies {
  api "com.badlogicgames.gdx:gdx-freetype:$gdxVersion"
  api "com.badlogicgames.gdx:gdx:$gdxVersion"
  api "com.github.raeleus.TenPatch:tenpatch:$tenPatchVersion"
  implementation "com.google.code.gson:gson:2.10.1"
  implementation 'com.github.yasin-2k7:libPVZ:d869ba9dbd51532ca16378ee62200111f3421156'
  implementation 'com.github.pizpizi:pvz-skin:v0.1.1'
  implementation 'com.github.raeleus.TenPatch:tenpatch:5.2.3'
  implementation 'com.fasterxml.jackson.core:jackson-databind:2.18.2'

  if(enableGraalNative == 'true') {
    implementation "io.github.berstanio:gdx-svmhelper-annotations:$graalHelperVersion"
  }
}

jar {
  duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}
